# Generated by Django 3.2.11 on 2022-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220213_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpeg', upload_to='thumbnails/'),
        ),
    ]
