# Generated by Django 3.2.11 on 2022-02-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follwer',
            new_name='follower',
        ),
    ]
